config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :posts do
    resources :comments
  end
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :image, presence: true
  has_attached_file :image, styles: { medium: '640px' }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  belongs_to :user
  validates :user_id, presence: true
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      flash[:success] = 'You put commented the hell out of the post!'
      redirect_back fallback_location: root_path
    else
      flash[:alert] = 'Check the comment form, something went wrong.'
      render root_path
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])

    @comment.destroy
    flash[:success] = 'Comment deleted :('
    redirect_to root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]
  before_action :owned_post, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = current_user.posts.build
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = 'Post updated.'
      redirect_to post_path(@post)
    else
      flash.now[:alert] = 'Update failed.  Please check the form.'
      render 'edit'
    end
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = 'Your post has been created!'
      redirect_to posts_path
    else
      flash.now[:alert] = "Your new post couldn't be created!  Please check the form."
      render 'new'
    end
  end

  def destroy
    if @post.destroy
      redirect_to posts_path
    else
      render 'show'
    end
  end

  private

  def post_params
    params.require(:post).permit(:image, :caption)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def owned_post
    unless current_user == @post.user
      flash[:alert] = "That post doesn't belog to you!"
      redirect_to root_path
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_for(flash_type)
    { success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="navbar-container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" 
        type="button">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to "Photogram", root_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to "New Post", new_post_path %>
          </li>
          <li>
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to "Login", new_user_session_path %>
          </li>
          <li>
            <%= link_to "Register", new_user_registration_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photogram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="form-wrapper">
  <%= simple_form_for @post, html: { class: 'form-horizontal', multiart: true } do |f| %>
    <div class="form-group">
      <%= f.input :image, label: 'post', input_html: { class: 'file form-control' } %>
    </div>
    <div class="form-group text-center">
      <%= f.input :caption, input_html: { class: 'form-control' } %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-head">
      <div class="thumb-img"></div>
      <div class="user-name">
        <%= post.user.user_name %>
      </div>
    </div>
    <div class="image center-block">
      <%= link_to (image_tag post.image.url(:medium), class:'img-responsive img-responsive-height center-image '), post_path(post) %>
    </div>
    <div class="post-bottom">
      <div class="caption">
        <div class="user-name">
          <%= post.user.user_name %>
        </div>
        <%= post.caption %>
      </div>
      <% if post.comments %>
        <% post.comments.each do |comment| %>
          <div class="comment">
            <div class="user-name">
              <%= comment.user.user_name %>
            </div>
            <div class="comment-content">
              <%= comment.content %>
            </div>
            <% if comment.user == current_user %>
              <%= link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" } do %>
                <span class="glyphicon glyphicon-remove delete-comment"></span>
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="comment-like-form row">
      <div class="like-button col-sm-1">
        <span class="glyphicon glyphicon-heart-empty"></span>
      </div>
      <div class="comment-form col-sm-11">
        <%= form_for [post, post.comments.new] do |f| %>
          <%= f.text_field :content, placeholder: 'Add a comment...', class: "form-control" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="text-center">
  <%= image_tag @post.image.url(:medium), class: "posts-wrapper" %>
</div>
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="posts-wrapper row">
  <% @posts.each do |post| %>
    <%= render 'post', post: post %>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="single-post-wrapper row">
  <%= render 'post', post: @post %>
  <div class="text-center edit-links">
    <%= link_to "Back", posts_path %>
    <% if user_signed_in? && @post.user.id == current_user.id %>
      |
      <%= link_to "Edit Post", edit_post_path(@post) %>
      |
      <%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
    <% end %>
  </div>
  </div>
</div>